### 문항 1 Numpy 배열로 5명 학생의 4과목 성적표를 만들고 축(axis) 기준 통계를 산출하시오.

아래 1차원 리스트는 학생 5명이 4개 과목(국어, 영어, 수학, 과학 순)에서 받은 점수를 이어 붙인 것입니다.

Numpy만 사용하여(반복문 사용 금지) 다음을 순서대로 수행하고 결과를 출력하세요.
```py
scores = [88, 92, 79, 95,
          75, 68, 82, 70,
          92, 99, 95, 88,
          60, 72, 65, 58,
          85, 80, 78, 90]
```

In [ ]:
# 1 위 리스트를 5행 4열 ndarray로 변환하고 shape, ndim, size, dtype을 출력하시오.
import numpy as np

scores = [88, 92, 79, 95,
          75, 68, 82, 70,
          92, 99, 95, 88,
          60, 72, 65, 58,
          85, 80, 78, 90]

s = np.array(scores).reshape(5, 4)
print(s)
print(s.shape, s.ndim, s.size, s.dtype)

[[88 92 79 95]
 [75 68 82 70]
 [92 99 95 88]
 [60 72 65 58]
 [85 80 78 90]]
(5, 4) 2 20 int64


In [ ]:
# 2 학생 별 평균과 과목 별 평균을 각각 구하시오.
student_avg = np.mean(s, axis=1)
subjects_avg = np.mean(s, axis=0)
print(student_avg) # 학생 별 평균 점수
print(subjects_avg) # 교과 별 평균 점수

[88.5  73.75 93.5  63.75 83.25]
[80.  82.2 79.8 80.2]


In [ ]:
# 3 전체에서 가장 높은 점수와 그 점수가 몇 번째 학생·몇 번째 과목인지 구하시오.
max_scores = np.max(s) # 전체 Max 값
max_arg = np.argmax(s) # Max 값 위치
max_pos = np.argwhere(s == max_scores)
print(max_scores)
print(max_pos)

99
[[2 1]]


In [ ]:
# 4 전체 평균, 표준편차, 분산을 구하시오.
x = s.mean() # 전체 평균
y = s.std() # 전체 표준편차
z = s.var() # 전체 분산
print(x, y, z)

80.55 11.825713509129164 139.84750000000003


In [ ]:
# 5 평균이 80점 이상인 학생의 인덱스와 인원수를 구하고, 해당 학생들의 성적만 잘라내어 출력하시오.
s_idx = np.where(student_avg >= 80) # 평균 80점 이상 학생 인덱스
print(s_idx, np.sum(student_avg >= 80)) # 인덱스와 인원수
print(s[s_idx]) # 평균 80점 이상 학생 점수만 출력

(array([0, 2, 4]),) 3
[[88 92 79 95]
 [92 99 95 88]
 [85 80 78 90]]


In [ ]:
# 6 90점 이상인 점수의 개수, 100점 이상인 점수가 하나라도 있는지, 모든 점수가 60점 이상인지를 판별하시오.
print(np.sum( s >= 90 ), np.sum( s >= 100 ), np.all( s >= 60))

6 0 False


In [ ]:
# 7 90점 이상은 'A', 80점 이상은 'B', 나머지는 'C'로 변환한 등급 배열을 만드시오.
grade = np.where(s>= 90, 'A', np.where(s >=80, 'B', 'C'))

print(grade)

[['B' 'A' 'C' 'A']
 ['C' 'C' 'B' 'C']
 ['A' 'A' 'A' 'B']
 ['C' 'C' 'C' 'C']
 ['B' 'B' 'C' 'A']]


### 문항 2 8x8 난수 배열을 흑백 이미지로 가정하고 슬라이싱 이진화 좌우 반전을 구현하시오.

0~255 사이의 정수 난수로 이루어진 8행 8열 배열을 흑백 이미지 데이터라고 가정합니다. 채점 결과를 동일하게 맞추기 위해 반드시 아래 시드를 먼저 실행하세요.
```py
import numpy as np
np.random.seed(2024)
img = np.random.randint(0, 256, size=(8, 8))
```

In [108]:
import numpy as np
np.random.seed(2024)
img = np.random.randint(0, 256, size=(8, 8))

In [109]:
# 1 생성한 img를 출력하시오.
print(img)

[[136 250  96 128  27  36 190 183]
 [ 41 127 193  60 227  74  66 224]
 [165 252 241 158 111 247 202 110]
 [ 95 111  11  28  91  39  54 114]
 [183  73 102 218 244  42  31  97]
 [150  27  86 119  69 157  61 243]
 [ 54 132  57  86  54 254 148 126]
 [136  18  97  90 202 135 176 232]]


In [ ]:
# 2 이미지 정중앙의 4×4 영역만 잘라내어 출력하시오.
print(img[2:6, 2:6])

[[241 158 111 247]
 [ 11  28  91  39]
 [102 218 244  42]
 [ 86 119  69 157]]


In [67]:
# 3 짝수 번째 행(0, 2, 4, 6행)만 뽑아내시오.
print(img[::2])

[[136 250  96 128  27  36 190 183]
 [165 252 241 158 111 247 202 110]
 [183  73 102 218 244  42  31  97]
 [ 54 132  57  86  54 254 148 126]]


In [72]:
# 4 128 이상인 픽셀은 255(흰색), 미만인 픽셀은 0(검은색)으로 바꾼 이진화 배열을 만드시오.
bw = np.where(img >= 128, 255, 0)
print(bw)

[[255 255   0 255   0   0 255 255]
 [  0   0 255   0 255   0   0 255]
 [255 255 255 255   0 255 255   0]
 [  0   0   0   0   0   0   0   0]
 [255   0   0 255 255   0   0   0]
 [255   0   0   0   0 255   0 255]
 [  0 255   0   0   0 255 255   0]
 [255   0   0   0 255 255 255 255]]


In [73]:
# 5 이진화 결과에서 흰색 픽셀과 검은색 픽셀의 개수를 각각 세시오.
print(np.sum(bw == 255), np.sum(bw == 0))

28 36


In [88]:
# 6 원본 이미지를 좌·우 절반으로 분할하시오.
img_split =np.split(img,2,axis=1)
print(f'원본 이미지 좌: \n {img_split[0]}')
print(f'원본 이미지 우: \n {img_split[1]}')

원본 이미지 좌: 
 [[136 250  96 128]
 [ 41 127 193  60]
 [165 252 241 158]
 [ 95 111  11  28]
 [183  73 102 218]
 [150  27  86 119]
 [ 54 132  57  86]
 [136  18  97  90]]
원본 이미지 우: 
 [[ 27  36 190 183]
 [227  74  66 224]
 [111 247 202 110]
 [ 91  39  54 114]
 [244  42  31  97]
 [ 69 157  61 243]
 [ 54 254 148 126]
 [202 135 176 232]]


In [94]:
# 7 분할한 두 조각의 순서를 바꿔 다시 이어 붙여 좌우가 뒤바뀐 이미지를 만드시오.
rev_img = np.concatenate([img_split[1], img_split[0]], axis=1)
print(rev_img)

[[ 27  36 190 183 136 250  96 128]
 [227  74  66 224  41 127 193  60]
 [111 247 202 110 165 252 241 158]
 [ 91  39  54 114  95 111  11  28]
 [244  42  31  97 183  73 102 218]
 [ 69 157  61 243 150  27  86 119]
 [ 54 254 148 126  54 132  57  86]
 [202 135 176 232 136  18  97  90]]


In [99]:
# 8 원본 이미지를 1차원으로 펼친 뒤 앞 10개 값과 shape을 출력하시오.
one_dim_img =img.ravel()
print(one_dim_img[:10], one_dim_img.shape)

[136 250  96 128  27  36 190 183  41 127] (64,)


In [ ]:
# 9 128 이상인 픽셀만 골라내어 그 개수와 평균값을 구하시오.
cnt = np.sum(img >= 128)
print(cnt)
img[img < 128 ] = 0
avg = np.sum(img) / cnt
print(avg)

28
193.07142857142858


In [114]:
cnt1 = img[img >= 128]
cnt1
print(np.size(cnt1), np.mean(cnt1))

28 193.07142857142858


### 문항 3 지점별 판매 데이터에 브로드캐스트와 행렬 연산을 적용해 매출을 분석하시오.
```py
sales = np.array([[120,  80,  45,  60],     # A지점
                  [200, 150,  90,  30],     # B지점
                  [ 75,  60, 120,  95]])    # C지점
price = np.array([1500, 3000, 5000, 2000])  # 제품 1~4 단가
```

In [117]:
sales = np.array([[120,  80,  45,  60],     # A지점
                  [200, 150,  90,  30],     # B지점
                  [ 75,  60, 120,  95]])    # C지점
price = np.array([1500, 3000, 5000, 2000])  # 제품 1~4 단가

In [127]:
#1 브로드캐스트를 이용해 각 지점의 제품별 매출액(수량 × 단가) 행렬을 구하시오. (반복문 금지)
print(sales * price)

[[180000 240000 225000 120000]
 [300000 450000 450000  60000]
 [112500 180000 600000 190000]]


In [136]:
#2 행렬곱을 이용해 각 지점의 총매출을 한 번에 구하시오. 또한 제품별 총판매량도 구하시오.
total_sales = sales.dot(price)
print(total_sales)
per_sales = sales.sum(axis=0)
print(per_sales)

[ 765000 1260000 1082500]
[395 290 255 185]


In [150]:
#3 각 제품의 평균 판매량을 구한 뒤, 브로드캐스트로 평균 대비 편차 행렬을 구하시오.
avg_sales = np.mean(sales, axis=0)
print(avg_sales)
print(sales - avg_sales)

[131.66666667  96.66666667  85.          61.66666667]
[[-11.66666667 -16.66666667 -40.          -1.66666667]
 [ 68.33333333  53.33333333   5.         -31.66666667]
 [-56.66666667 -36.66666667  35.          33.33333333]]


In [162]:
#4 각 지점을 기준으로 판매량을 정규화하시오. 결과의 행별 평균이 0, 표준편차가 1이 되는지 확인하시오.
per_mean = np.mean(sales, axis=1, keepdims=True)
print(per_mean)
per_std = np.std(sales, axis=1, keepdims=True)
print(per_std)
sales_normalized = (sales - per_mean) / per_std
print(sales_normalized)

[[ 76.25]
 [117.5 ]
 [ 87.5 ]]
[[28.14582562]
 [63.78675411]
 [22.5       ]]
[[ 1.55440457  0.13323468 -1.11028898 -0.57735027]
 [ 1.29337197  0.50951017 -0.43112399 -1.37175815]
 [-0.55555556 -1.22222222  1.44444444  0.33333333]]


In [164]:
print('행별 평균:', np.mean(sales_normalized, axis=1).round(2))
print('행별 표준편차:', np.std(sales_normalized, axis=1).round(2))

행별 평균: [ 0.  0. -0.]
행별 표준편차: [1. 1. 1.]


In [ ]:
#5 sales의 전치행렬을 구하고 shape을 출력하시오.
print(sales.T) # 전치행렬
print(sales.T.shape) # 전치행렬의 shape


[[120 200  75]
 [ 80 150  60]
 [ 45  90 120]
 [ 60  30  95]]
(4, 3)


In [ ]:
#6 sales의 앞 3개 열만 잘라 3×3 정방행렬 A를 만들고, 행렬식과 역행렬을 구하시오. 이어서 A와 역행렬을 곱해 단위행렬이 나오는지 확인하시오.
A = sales[:3, :3] #정방행렬
print(A)

[[120  80  45]
 [200 150  90]
 [ 75  60 120]]


In [ ]:
x = np.linalg.det(A)
print(x) #행렬식

165749.9999999999


In [ ]:
inv_A = np.linalg.inv(A)
print(inv_A) # A의 역행렬

[[ 0.0760181  -0.04162896  0.00271493]
 [-0.1040724   0.06651584 -0.01085973]
 [ 0.00452489 -0.00723982  0.01206637]]


In [ ]:
print((A @ inv_A).round(1)) # 단위행렬

[[ 1. -0. -0.]
 [ 0.  1. -0.]
 [ 0. -0.  1.]]


In [193]:
#7 총매출이 가장 높은 지점의 인덱스와, 지점 순서대로의 누적 매출을 구하시오.
print('총매출이 가장 높은 지점의 인덱스:', np.argmax(total_sales))
print('지점 순서대로 누적 매출:', np.cumsum(total_sales))

총매출이 가장 높은 지점의 인덱스: 1
지점 순서대로 누적 매출: [ 765000 2025000 3107500]
